### ISSUE TITLE
ArduinoIDE >V2 lässt kein LittleFS data upload zu

### ISSUE THREAD

**Issue by pippcat** [Fabmobil/Pflanzensensor#8]
- Das Hochladen der LittleFS Datenpartition funktioniert OOTB nur mit der Arduino IDE V1.8. Versionen >2 können das nicht.
- Oder eventuell doch, mit diesem Plugin: https://github.com/earlephilhower/arduino-littlefs-upload ?
- Ansonsten gibt es hier etwas dazu zu lesen: https://forum.arduino.cc/t/littlefs-data-upload-in-arduino-2-x-x/1174393/2
- Auf den Laptops im Fabmobil ist V2.3.1 installiert.
- Zur Show muss das funktionieren
- die Doku muss entsprechend angepasst werden.

**Comment by Fabmobil** [comment]
Funktioniert mit diesem Plugin wie beschrieben: https://github.com/earlephilhower/arduino-littlefs-upload
